apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-fastapi
  template:
    metadata:
      labels:
        app: minio-fastapi
    spec:
      containers:
        - name: app
          image: minio-fastapi-demo:latest
          ports:
            - containerPort: 8000
          env:
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: secretkey
            - name: MINIO_SECURE
              value: "False"
            - name: BUCKET_NAME
              value: "testbucket"
